version: "3.9"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      # development
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      # providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # redirect http to https
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure" 
      # enable https
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"      
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=nickp2287@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # enable https
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  resume2021-final:
    image: nickp2287apps/resume2021-final
    container_name: resume2021-final
    depends_on: 
      - traefik
    environment: 
      - 'PORT=1111'
    labels: 
      - "traefik.enable=true"
      # - "traefik.http.routers.resume2021.entrypoints=web"
      - "traefik.http.routers.resume2021.rule=Host(`localhost`)"
      - "traefik.http.services.resume2021.loadbalancer.server.port=1111"
      # enable https
      - "traefik.http.routers.resume2021.entrypoints=websecure"
      - "traefik.http.routers.resume2021.tls.certresolver=myresolver"

  simple-ecommerce-final:
    image: nickp2287apps/simple-ecommerce-final
    container_name: simple-ecommerce-final
    depends_on: 
      - traefik
    environment: 
      - 'PORT=2222'
    labels: 
      - "traefik.enable=true"
      # - "traefik.http.routers.simple-ecommerce.entrypoints=web"
      - "traefik.http.routers.simple-ecommerce.rule=Host(`simple-ecommerce.localhost`)"
      - "traefik.http.services.simple-ecommerce.loadbalancer.server.port=2222"
      # enable https
      - "traefik.http.routers.simple-ecommerce.entrypoints=websecure"
      - "traefik.http.routers.simple-ecommerce.tls.certresolver=myresolver"
    

  # Example
  test:
    image: "nickp2287apps/ls-test"
    container_name: "test"
    depends_on: 
      - traefik
    environment:
      - "PORT=5555"
    # networks: 
    #   - example
    # ports:
    #   - "5555:5555"
    # volumes:
    #   - ./:/app
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.test.entrypoints=web"
      - "traefik.http.routers.test.rule=PathPrefix(`/test`)"
      - "traefik.http.services.test.loadbalancer.server.port=5555"
      # enable https
      - "traefik.http.routers.test.entrypoints=websecure"
      - "traefik.http.routers.test.tls.certresolver=myresolver"

# networks:
#   example:
# volumes: 
#   db: